language: python
matrix:
  include:
    # Run the tests for every version of python on the default OS (linux).
    # "python:" tells Travis what version to use, and
    # "env:" variables are exported, where tox picks them up.
    # The versions must match, or tox won't be able to find the correct
    # interpreter
    - name: "Python 3.4 on Linux"
      python: 3.4
      env: TOXENV=py34
    - name: "Python 3.5 on Linux"
      python: 3.5
      env: TOXENV=py35
    - name: "Python 3.6 on Linux"
      python: 3.6
      env: TOXENV=py36
    - name: "Python 3.7 on Linux"
      python: 3.7
      env: TOXENV=py37
    - name: "Python 3.8 on linux"
      python: 3.8
      env: TOXENV=py38

    - name: "Python 3.7 on macOS 10.13"
      os: osx
      osx_image: xcode9.4
      language: shell  # 'language: python' errors on Travis CI macOS
      env: TOXENV=py37
    - name: "Python 3.7 on macOS 10.14"
      os: osx
      osx_image: xcode10.2
      language: shell  # 'language: python' errors on Travis CI macOS
      env: TOXENV=py37

    - name: "Python 3.5 on Windows"
      os: windows
      language: shell   # 'language: python' errors on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python -m pip install --upgrade pip
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH TOXENV=py35
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell   # 'language: python' errors on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH  TOXENV=py36
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell   # 'language: python' errors on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH  TOXENV=py37

    # For generating docs and linting we only care about a recent python.
    - name: "Ensure docs build"
      python: 3.8
      env: TOXENV=docs
    - name: "Run flake8"
      python: 3.8
      env: TOXENV=flake8


install:
  - pip3 install tox
script:
  - tox
